name: d8-high-contrast
recipe: drupal9
config:
  webroot: web
  php: '8.1'
  database: mysql:5.7
  xdebug: debug
tooling:
  drush:
    service: appserver
    cmd:
      - "drush --uri=https://d8-high-contrast.lndo.site"
  grumphp:
    service: appserver
    description: Runs grumphp commands
    cmd: /app/.lando/tooling-grumphp.sh

# Recommended Lando version.
version: v3.6.4
