name: d8-high-contrast
recipe: drupal8
config:
  webroot: web
  php: '7.4'
  database: mysql:5.7
  xdebug: debug
tooling:
  drush:
    service: appserver
    cmd:
      - "drush --uri=http://d8-high-contrast.lndo.site"
  grumphp:
    service: appserver
    description: Runs grumphp commands
    cmd: /app/.lando/tooling-grumphp.sh

# Recommended Lando version.
version: v3.0.0-rrc.2
